Fix warnings and add social links
shellhub-io/website-v2 pull request #4
Opened 2021-03-20 00:36 UTC by Domarys

Signed-off-by: Domarys Correa <domaryscorrea@gmail.com>

Corrigido os warnings relativos ao código. Ficam três relativos aos pacotes.

2021-03-20 00:48 UTC, otavio requested changes

2021-03-20 00:48 UTC, otavio commented on src/components/Header/index.js
> +/* using de disable command to stop the warning about the variable not used - the use of this import is necessary to JSX*/
Please consider adding a smaller comment when silencing the warnings. Something like:
```js
/* Silent warning asimport is necessary for JSX */
```

2021-03-22 12:05 UTC, Domarys commented
@otavio pode me confirmar se os comments estão bons?

2021-03-24 18:14 UTC, leonardojoao approved these changes

2021-03-24 18:21 UTC, otavio approved these changes

2021-03-24 18:21 UTC, merged